export interface BlogPostMeta {
  slug: string
  title: string
  description: string
  date: string
  readTime: string
  keywords: string[]
  related?: string[]
}

export const BLOG_POSTS_A: BlogPostMeta[] = [
  {
    slug: 'cio-search-signal-story-sequence',
    title: 'Executive Search For CIO Candidates: Signal, Story, And Sequence',
    description: 'A practical CIO search model that combines signal monitoring, role narrative design, and a consistent execution sequence.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'cio executive search strategy',
      'cio search process',
      'c-suite signal monitoring',
      'executive narrative strategy',
      'cio search cadence',
    ],
    related: ['executive-search-timing-signals', 'c-suite-search-90-day-plan', 'how-cios-find-jobs'],
  },
  {
    slug: 'executive-search-pilot-data-observations',
    title: 'Pilot Data: What We Observed Across Executive Search Campaigns',
    description: 'A summary of pilot cohort observations, including what improved, where variance appeared, and how to interpret limits responsibly.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'executive search pilot data',
      'executive search outcomes',
      'c-suite pilot observations',
      'search campaign performance data',
      'executive transition cohort results',
    ],
    related: ['pilot-findings', 'executive-search-consistency-model', 'c-suite-search-weekly-metrics'],
  },
  {
    slug: 'evidence-hub-coaching-session-framework',
    title: 'How To Use Evidence Hub In Weekly Executive Coaching Sessions',
    description: 'A weekly coaching session framework that uses evidence-backed claims, explicit assignments, and measurable review loops.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive coaching session framework',
      'coaching agenda template executives',
      'evidence based coaching sessions',
      'executive coaching weekly cadence',
      'coaching accountability structure',
    ],
    related: ['evaluate-executive-coach-evidence', 'executive-coaching-search-outcomes', 'coaching-effectiveness'],
  },
  {
    slug: 'executive-search-risk-register',
    title: 'Executive Search Risk Register: The 10 Failure Modes To Watch',
    description: 'A practical risk register for senior search campaigns with early warning indicators, mitigation actions, and weekly review rules.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'executive search risks',
      'c-suite search risk register',
      'executive transition failure modes',
      'search campaign mitigation plan',
      'executive search risk review',
    ],
    related: ['executive-search-readiness-audit', 'c-suite-search-weekly-metrics', 'executive-search-consistency-model'],
  },
  {
    slug: 'executive-hiring-committee-psychology',
    title: 'Hiring Committee Psychology: What Senior Candidates Should Anticipate',
    description: 'How hiring committees reduce uncertainty in senior hiring, and how candidates can improve decision confidence through signal quality and narrative precision.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive hiring committee decision process',
      'senior hiring psychology',
      'c-suite interview decision dynamics',
      'executive candidate uncertainty reduction',
      'hiring committee strategy',
    ],
    related: ['executive-search-timing-signals', 'executive-outreach-response-rate', 'executive-interview-prep-7-day-system'],
  },
  {
    slug: 'source-backed-executive-career-narrative',
    title: 'Building A Source-Backed Executive Career Narrative',
    description: 'A framework for creating executive career narratives tied to evidence, role context, and measurable business impact before interviews begin.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'executive career narrative framework',
      'source backed executive positioning',
      'c-suite narrative strategy',
      'executive interview story framework',
      'evidence based leadership narrative',
    ],
    related: ['vp-to-c-suite-positioning', 'executive-organizational-visibility', 'executive-transition-success-factors'],
  },
  {
    slug: 'c-suite-search-weekly-metrics',
    title: 'What To Track Weekly In A C-suite Search (With Benchmarks)',
    description: 'A practical weekly scorecard for executive search campaigns, including leading and lagging indicators, benchmark ranges, and intervention thresholds.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'c suite job search metrics',
      'executive search benchmarks',
      'executive search weekly dashboard',
      'c-suite search scorecard',
      'executive campaign metrics',
    ],
    related: ['executive-search-consistency-model', 'executive-job-search-daily-routine', 'pilot-findings'],
  },
  {
    slug: 'executive-outreach-response-rate',
    title: 'Why Executive Outreach Gets Ignored And How To Fix It',
    description: 'Most senior outreach fails because it lacks context, relevance, and timing discipline. This guide shows how to improve response rates without increasing volume.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive outreach response rate',
      'executive networking messaging',
      'c-suite outreach strategy',
      'executive message framing',
      'improve recruiter response rate',
    ],
    related: ['why-executive-recruiters-go-quiet', 'evidence-based-executive-networking', 'executive-organizational-visibility'],
  },
  {
    slug: 'c-suite-search-90-day-plan',
    title: 'C-suite Search Timeline: What To Do In Days 1-30, 31-60, 61-90',
    description: 'A phased 90-day plan for executive search execution with concrete priorities for setup, momentum, and conversion in each stage.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'c suite search timeline',
      'executive search 90 day plan',
      'c-suite transition plan',
      'executive search phases',
      'senior search execution plan',
    ],
    related: ['executive-search-timing-signals', 'executive-search-consistency-model', 'executive-transition-success-factors'],
  },
  {
    slug: 'evidence-based-executive-networking',
    title: 'Evidence-Based Executive Networking: A Practical Cadence For Busy Leaders',
    description: 'A relationship activation model for senior leaders that uses contact tiers, message objectives, and weekly cadence to maintain momentum.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive networking strategy',
      'c-suite networking cadence',
      'executive relationship management',
      'senior leader networking plan',
      'executive outreach cadence',
    ],
    related: ['executive-organizational-visibility', 'executive-outreach-response-rate', 'linkedin-executive-search-strategy'],
  },
  {
    slug: 'executive-search-readiness-audit',
    title: 'Executive Search Readiness Audit: 15 Questions Before You Start',
    description: 'Use a structured readiness audit before launching your campaign so you can identify gaps, score risk, and fix bottlenecks in two weeks.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'executive search readiness checklist',
      'c-suite readiness audit',
      'executive transition preparation',
      'executive search risk assessment',
      'senior candidate readiness',
    ],
    related: ['executive-transition-success-factors', 'c-suite-search-90-day-plan', 'executive-interview-prep-7-day-system'],
  },
  {
    slug: 'vp-to-c-suite-positioning',
    title: 'VP To C-suite Positioning: How To Show Enterprise-Level Scope',
    description: 'The VP-to-C-suite move requires enterprise-level narrative, board-facing framing, and proof of cross-functional business impact.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'vp to c suite positioning',
      'vp to c-suite transition strategy',
      'executive positioning for promotion',
      'enterprise scope narrative',
      'c-suite readiness positioning',
    ],
    related: ['vp-to-cio-transition', 'executive-transition-success-factors', 'executive-organizational-visibility'],
  },
  {
    slug: 'executive-organizational-visibility',
    title: 'Organizational Visibility For Executives: What Actually Creates Momentum',
    description: 'Visibility at the executive level is not broadcasting. It is disciplined context-sharing with the right stakeholders at the right cadence.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive visibility strategy',
      'organizational visibility executives',
      'executive relationship momentum',
      'c-suite visibility',
      'executive stakeholder communication',
    ],
    related: ['linkedin-executive-search-strategy', 'how-cios-find-jobs', 'executive-search-operating-system'],
  },
  {
    slug: 'confidential-executive-search-pipeline',
    title: 'Confidential Executive Search: How To Build Pipeline Without Public Signaling',
    description: 'A confidential search needs private signal monitoring, deliberate contact segmentation, and low-leak outreach patterns that preserve optionality.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'confidential executive job search',
      'private executive search strategy',
      'confidential c-suite search',
      'executive outreach confidentiality',
      'executive search pipeline private',
    ],
    related: ['how-cios-find-jobs', 'retained-search-firms', 'executive-search-operating-system'],
  },
  {
    slug: 'evaluate-executive-coach-evidence',
    title: 'How To Evaluate An Executive Coach Using Evidence, Not Marketing Copy',
    description: 'Coach selection improves when you score methods, measurement discipline, and between-session execution support instead of relying on credentials alone.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'how to choose executive coach',
      'evaluate executive coach',
      'executive coaching criteria',
      'executive coach selection framework',
      'evidence based coaching evaluation',
    ],
    related: ['executive-coaching-search-outcomes', 'executive-coaching-job-search', 'executive-coaching-candidate-infrastructure'],
  },
  {
    slug: 'executive-interview-prep-7-day-system',
    title: 'Executive Interview Prep: The 7-Day Briefing System',
    description: 'A one-week prep structure that improves conversation quality by combining company context, mandate framing, risk anticipation, and role-specific proof.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive interview preparation system',
      'c-suite interview prep',
      'executive briefing system',
      'interview prep for executives',
      'role specific executive preparation',
    ],
    related: ['ciso-interview-preparation', 'executive-transition-success-factors', 'executive-search-operating-system'],
  },
  {
    slug: 'executive-search-timing-signals',
    title: 'Executive Search Timing Signals: What Appears Before a Role Is Posted',
    description: 'The strongest executive opportunities are often visible through weak signals before a formal posting appears. Here is what to watch and how to act without overreacting to noise.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive search timing signals',
      'early role signals',
      'pre-posting executive opportunities',
      'executive hiring signal detection',
      'executive transition timing',
    ],
    related: ['how-we-estimate-early-role-signals', 'target-company-list', 'cio-job-market-2026'],
  },
  {
    slug: 'executive-coaching-search-outcomes',
    title: 'Does Executive Coaching Improve Search Outcomes? What The Evidence Shows',
    description: 'Executive coaching can improve outcomes when it is paired with clear operating cadence, explicit commitments, and role-specific preparation. This is what the evidence supports and where it does not.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive coaching effectiveness job search',
      'executive coaching outcomes',
      'coaching and executive transitions',
      'executive search coaching evidence',
      'leadership coaching job search',
    ],
    related: ['executive-coaching-job-search', 'executive-coaching-candidate-infrastructure', 'pilot-findings'],
  },
  {
    slug: 'executive-transition-success-factors',
    title: 'Executive Transition Success Factors: What Predicts Better Outcomes',
    description: 'Transition success is shaped by preparation depth, signal timing, and execution consistency. Here are the factors that matter most in the first 90 days of a search campaign.',
    date: '2026-06-23',
    readTime: '8 min read',
    keywords: [
      'executive transition success factors',
      'executive onboarding and transition',
      'c-suite transition outcomes',
      'executive search success drivers',
      'senior leadership transition strategy',
    ],
    related: ['vp-to-cio-transition', 'executive-search-operating-system', 'pilot-findings'],
  },
  {
    slug: 'executive-search-consistency-model',
    title: 'Behavior Change For Senior Candidates: Why Consistency Beats Intensity',
    description: 'Most executive campaigns stall from drift, not effort. Consistent weekly execution beats short bursts of high activity when the search timeline is long and uncertain.',
    date: '2026-06-23',
    readTime: '7 min read',
    keywords: [
      'executive job search consistency',
      'executive search behavior change',
      'c-suite search cadence',
      'executive campaign discipline',
      'executive search weekly model',
    ],
    related: ['executive-job-search-daily-routine', 'executive-search-operating-system', 'pilot-findings'],
  },
  {
    slug: 'executive-hiring-patterns-2026',
    title: 'We Analyzed 300+ Executive Hiring Profiles. Here Is What Actually Gets Senior Leaders Interviewed.',
    description: 'Most executive candidates still position around tenure and title. Hiring teams at the C-suite and VP level screen for transformation evidence, cross-functional influence, and business outcomes. Here is what the data says.',
    date: '2026-05-15',
    readTime: '6 min read',
    keywords: [
      'executive hiring trends 2026',
      'C-suite hiring patterns',
      'VP hiring criteria',
      'executive positioning strategy',
      'what gets executives interviewed',
      'senior leadership recruiting signals',
      'executive job search data',
    ],
    related: ['executive-resume-gaps', 'linkedin-executive-search-strategy', 'executive-job-search-daily-routine'],
  },
  {
    slug: 'why-executive-recruiters-go-quiet',
    title: 'Why Executive Recruiters Go Quiet (And How Senior Candidates Can Break the Pattern)',
    description: 'Strong candidates are often ignored for reasons that have little to do with capability and everything to do with decision pressure. The frame you use in outreach can reduce that pressure and increase response rates.',
    date: '2026-05-15',
    readTime: '6 min read',
    keywords: [
      'executive recruiter ghosting',
      'executive outreach response rate',
      'C-suite candidate messaging',
      'VP candidate outreach strategy',
      'how to message executive recruiters',
      'senior candidate outreach framework',
      'executive search communication',
    ],
    related: ['retained-search-firms', 'executive-search-firms-cio', 'linkedin-executive-search-strategy'],
  },
  {
    slug: 'why-starting-monday-exists',
    title: 'Why Starting Monday Exists: Executive Search Is Not a Resume Problem',
    description: 'C-suite and VP searches are won on specificity, timing, and preparation quality. We built Starting Monday to replace generic templates with role-specific positioning and high-context execution.',
    date: '2026-05-15',
    readTime: '5 min read',
    keywords: [
      'why starting monday exists',
      'executive search operating system',
      'C-suite search strategy',
      'VP executive transition',
      'executive positioning infrastructure',
      'senior leadership career transition',
      'how to run executive job search',
    ],
    related: ['executive-search-operating-system', 'target-company-list', 'executive-job-search-daily-routine'],
  },
  {
    slug: 'how-we-estimate-early-role-signals',
    title: 'How We Estimate Early Role Signals (And Why We Use a 1-3 Week Window)',
    description: 'A transparent look at our methodology: how we define event dates, posting dates, lag windows, and the primary sources we use to estimate early executive-role timing signals.',
    date: '2026-05-13',
    readTime: '6 min read',
    keywords: [
      'executive role timing methodology',
      'how we estimate job posting lead time',
      '8-K hiring signals',
      'career page monitoring method',
      'executive search timing signals',
      'decision to posting lag',
      'C-suite hiring signal model',
    ],
    related: ['cio-job-market-2026', 'target-company-list', 'executive-search-firms-cio'],
  },
  {
    slug: 'executive-job-search-daily-routine',
    title: 'Executive Job Search Daily Routine: What the Top 1% Do Differently',
    description: 'The strongest executive candidates run a disciplined daily operating rhythm: signals, targeted outreach, prep, and follow-through. Here is the exact routine and the weekly metrics that keep momentum high.',
    date: '2026-05-12',
    readTime: '6 min read',
    keywords: [
      'executive job search daily routine',
      'daily executive search workflow',
      'CIO job search habits',
      'executive search discipline',
      'how top executive candidates run search',
      'executive outreach routine',
      'senior candidate job search strategy',
      'executive search operating cadence',
    ],
    related: ['executive-search-operating-system', 'how-cios-find-jobs', 'linkedin-executive-search-strategy'],
  },
  {
    slug: 'executive-search-firms-cio',
    title: 'What Executive Search Firms Actually Want from C-suite Candidates',
    description: 'Most technology executives think about executive search firms the wrong way. Here is how retained search actually works, what gets you on the short list, and why timing matters more than almost anything else.',
    date: '2026-05-06',
    readTime: '6 min read',
    keywords: [
      'executive search firms C-suite',
      'how to work with executive search firms',
      'C-suite search firms',
      'what executive recruiters want',
      'C-suite job search strategy',
      'retained executive search',
      'how to get on C-suite short list',
    ],
    related: ['retained-search-firms', 'how-cios-find-jobs', 'cio-job-search-timeline'],
  },
]
